### ISSUE TITLE
5 not horizontally aligned 

### ISSUE THREAD

**Issue by jonmorazav** [HackFSU/hackfsu_com#18]
The 5 appears to be off center in relation to the other letters.  Was able to reproduce it on Chrome/Opera/Edge/IE using Windows 10.

![image](https://user-images.githubusercontent.com/17746797/28243396-cbedcd72-6995-11e7-88ec-bd0b441ca838.png)

**Comment by andrewsosa** [comment]
just noticed this is on the wrong repo, should go under https://github.com/HackFSU/HackFSU-Preview/issues/
