### ISSUE TITLE
Add routes for adding/editing announcements

### ISSUE THREAD

**Issue by Randy424** [HackFSU/hackfsu_com#22]

**Comment by whatsthedhillo** [comment]
I take that back, I'm not on slack yet. Whoops.

**Comment by andrewsosa** [comment]
Maybe set the ApiView to allow POST and GET, while PublicApiView only allows GET

**Comment by andrewsosa** [comment]
- [ ] create `/api/views/hackathon/updates` folder
- [ ] move `/api/views/hackathon/get/updates.py` to `/api/views/hackathon/updates/get.py`
- [ ] create `/api/views/hackathon/updates/post.py` for creating
- [ ] create `/api/views/hackathon/updates/patch.py` for updating

**Comment by andrewsosa** [comment]
This is going to be integrated into #67

**Comment by andrewsosa** [comment]
Implemented along with #67 in 20dbfbb304aef9e29015711f1565517634037e1c
