### ISSUE TITLE
Improve initial page load time

### ISSUE THREAD

**Issue by jrdbnntt** [HackFSU/hackfsu_com#9]
It takes a while to load the page. We can probably do some improvements and cleanup + improve the caching. I MAY have disabled  Cloudflare caching a long time ago when I was learning how to do it (or made it too short). 

It looks kind bad at first, especially with the font. We could switch to using CDN's with a local fallback too.

**Comment by andrewsosa** [comment]
This may be resolved via our plan of extracting the webapp to a Nodejs instance.

**Comment by andrewsosa** [comment]
Implemented in #46
